version: '3.3'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
        POSTGRES_DB: movie_search_db
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password123
    restart: unless-stopped

volumes:
  db-data:
    driver: local