server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie_search_db
    username: root
    password: password123
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/master.xml
    contexts: dev
  batch:
    initialize-schema: never